export {default as Home } from '../pages/Home'
export {default as HelpUs } from './help-us'
export {default as PreferUs } from '../pages/prefer-us'
export {default as Ensure } from '../pages/we-ensure'
export {default as Internet } from '../pages/Internet'
export {default as TotalExperience } from '../pages/TotalExperience'
export {default as Intelligent } from '../pages/Intelligent'
export {default as Cybersecurity } from '../pages/Cybersecurity'
export {default as Privacy } from '../pages/Privacy'
export {default as AIEngineering } from '../pages/AIEngineering'
export {default as Operation } from '../pages/Operation'
export {default as HyperAutomation } from '../pages/HyperAutomation'
export {default as WhyUsPage } from '../pages/whyUsPage'
export {default as CTO } from '../pages/CTO'
export {default as ValidationType } from '../pages/ValidationType'
export {default as Portfolio } from '../pages/Portfolio'

