
import {cirlceCancel,bulb,checkMark} from './assets'

export const whyUsItem= [
    {
        id:1,
        heading:'The most common pitfall in the death cycle are:',
        iconItems:[
            {icon:cirlceCancel, text:'Developers are expensive'},
            {icon:cirlceCancel, text:'To afford great developers,you need funding'},
            {icon:cirlceCancel, text:'To get traction, you need great developers'},
            {icon:cirlceCancel, text:'Turning to offshore, cheap developers that drain time and money'},
            {icon:cirlceCancel, text:'Most founders burn valuable cash in the pre-Series A cycle of death'},
            {icon:cirlceCancel, text:'To get funding, you need traction'},
            {icon:cirlceCancel, text:'Locking in off-the-shelf software that breaks under basic needs'},
            {icon:cirlceCancel, text:'Chasing great, local talent who will never leave cushy jobs'},
        ],
        imageUrl:bulb,
        subtitle:'We made these mistakes. They sucked. Until we learned that…',
        subHeading:'we help by',
        contentItems:[
            {icon:checkMark, text:'Being your interim, ad-hoc, fractional, virtual, remote, part-time, temp CTO and tech team'},
            {icon:checkMark, text:'Grow the company'},
            {icon:checkMark, text:'Scoping and prototyping'},
            {icon:checkMark, text:'Establishing an exceptional engineering process'},
            {icon:checkMark, text:'Focus on strong soft skills'},
            {icon:checkMark, text:'Product/Market Fit Pivot Pointing for early-stage founders'},
        ],
    },
    // {
    //     id:2,
    //     heading:'The most common pitfall in the death cycle are:',
    //     iconItems:[
    //         {icon:cirlceCancel, text:'Developers are expensive'},
    //         {icon:cirlceCancel, text:'To afford great developers,you need funding'},
    //         {icon:cirlceCancel, text:'To get traction, you need great developers'},
    //         {icon:cirlceCancel, text:'Turning to offshore, cheap developers that drain time and money'},
    //         {icon:cirlceCancel, text:'Most founders burn valuable cash in the pre-Series A cycle of death'},
    //         {icon:cirlceCancel, text:'To get funding, you need traction'},
    //         {icon:cirlceCancel, text:'Locking in off-the-shelf software that breaks under basic needs'},
    //         {icon:cirlceCancel, text:'Chasing great, local talent who will never leave cushy jobs'},
    //     ],
    //     imageUrl:bulb,
    //     subtitle:'We made these mistakes. They sucked. Until we learned that…',
    //     subHeading:'why prefer us?',
    //     contentItems:[
    //         {icon:checkMark, text:'We are investor friendly'},
    //         {icon:checkMark, text:'We partner with founders and their teams.'},
    //         {icon:checkMark, text:'We build great technology products.'},
    //         {icon:checkMark, text:'We don’t waste your money on consultancy slide decks.'},
    //         {icon:checkMark, text:'We create well-document,robust products.'},
    //         {icon:checkMark, text:'We assist in the transition to in-sourced teams.'},
    //     ],
    // },
    // {
    //     id:3,
    //     heading:'The most common pitfall in the death cycle are:',
    //     iconItems:[
    //         {icon:cirlceCancel, text:'Developers are expensive'},
    //         {icon:cirlceCancel, text:'To afford great developers,you need funding'},
    //         {icon:cirlceCancel, text:'To get traction, you need great developers'},
    //         {icon:cirlceCancel, text:'Turning to offshore, cheap developers that drain time and money'},
    //         {icon:cirlceCancel, text:'Most founders burn valuable cash in the pre-Series A cycle of death'},
    //         {icon:cirlceCancel, text:'To get funding, you need traction'},
    //         {icon:cirlceCancel, text:'Locking in off-the-shelf software that breaks under basic needs'},
    //         {icon:cirlceCancel, text:'Chasing great, local talent who will never leave cushy jobs'},
    //     ],
    //     imageUrl:bulb,
    //     subtitle:'We made these mistakes. They sucked. Until we learned that…',
    //     subHeading:'we ensure',
    //     listItems:[
    //         {icon:checkMark, text:'Lightning fast iteration'},
    //         {icon:checkMark, text:'Absurdly low cost'},
    //         {icon:checkMark, text:'Time for user feedback'},
    //         {icon:checkMark, text:'Grow the company'},
    //         {icon:checkMark, text:'Focus on strong soft skills'},
    //         {icon:checkMark, text:'Founder-friendly services'},
    //         {icon:checkMark, text:'Launch a fully functional product in weeks'},
    //         {icon:checkMark, text:'Transparent pricing. Break the pre-series A cycle of death.'},
    //         {icon:checkMark, text:'From web to mobile apps, we can build all the software workflows you need to delight your customers'},
    //     ],
    // },
]


